server:
  port: 8080

integration:
  security:
    basicAuth:
      username: ${SECURITY_USER}
      password: ${SECURITY_PASS}
  wiremock:
    baseUrl: ${WIREFRAME_HOST}
    port: ${WIREFRAME_PORT}

spring:
  flyway:
    enabled: true
    locations: classpath:migration
    baselineOnMigrate: true
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
