server:
  port: 8080

management:
  endpoints:
    web.exposure.include: info, health
  metrics:
    distribution:
      percentiles-histogram:
        http: true
        resilience4j:
          retry.calls: true

integration:
  wiremock:
    baseUrl: app-wiremock
