server:
  port: 8080

management:
  endpoints:
    web.exposure.include: info, health
  metrics:
    distribution:
      percentiles-histogram:
        http: true
        resilience4j:
          retry.calls: true

integration:
  security:
    basicAuth:
      username: admin
      password: admin
  wiremock:
    baseUrl: localhost
    port: 8081
